export const getMiCarreraDev = () => [
  {
    id: '1',
    titulo: 'Angular',
    lugar: 'Educacion IT',
    tiempo: '',
    lugaresp: '',
    otros: 'Detalles:',
    detalle1: '•	Herramientas angular CLI - Arquitectura de una aplicación Angular ',
    detalle2: '•  Modelos de Formularios y sus validaciones',
    detalle3: '•  Inyección de Dependencias - crear servicios inyectables - Jerarquia de Servicios',
    detalle4: '•	Configuracion del cliente http - obtener datos de un JSON - ActivatedRoute - RouterModule  ',
    logo: 'https://i.ibb.co/pwW6x1x/Screenshot-1.png',
  },
  {
    id: '2',
    titulo: 'ReactJS',
    lugar: 'Educacion IT',
    tiempo: '',
    lugaresp: '',
    otros: 'Detalles:',
    detalle1: '•	Desarrollo con ReactJS ',
    detalle2: '•  Uso de: Componentes, Props y States ',
    detalle3: '•  Renderización desde el lado del cliente',
    detalle4: '•	Implementación de Redux y Routers ',
    logo: 'https://i.ibb.co/XtRZLVm/4.png',
  },
  {
    id: '3',
    titulo: 'Javascript Desarrollador Avanzado',
    lugar: 'Educación IT',
    tiempo: ' ',
    lugaresp: '',
    otros: 'Conocimientos principales:',
    detalle1: '•	Eventos - Formularios y Validaciones con expresiones regulares',
    detalle2: '•	AJAX - Promesas - Fetch API - AsyncAwait',
    detalle3: '•	Prototipos - Programación orientada a objetos',
    detalle3: '•	Patrones de diseño',
    logo: 'https://i.ibb.co/GnJ4q7x/descarga.png',
  },
  {
    id: '4',
    titulo: 'JavaScript AWP',
    lugar: 'Educación IT',
    tiempo: '',
    lugaresp: '',
    otros: 'Detalles:',
    detalle1: '•	Desarrollo de aplicaciones con la posibilidad de trabajar sin conexión',
    detalle2: '•  Desarrollo de aplicaciones con apariencia de una app nativa instalada en el celular',
    logo: 'https://i.ibb.co/GCL82Z7/11png.png',
  },

    {
      id: '5',
      titulo: 'Maquetado Web Avanzado - HTML5 y CSS3',
      lugar: 'Educación IT',
      tiempo: '',
      lugaresp: '',
      otros: 'Detalles:',
      detalle1: '• Diseños web responsivos',
      detalle2: '• Utilización de Bootstrap y Material',
      detalle3: '• APIs de dibujo (SVG, Canvas) - Diferente representación de colores y degradados',
      detalle4: '• Otros: Displays, Positions , Sprites, Animaciones, etc.',
      logo: 'https://i.ibb.co/0ZSF2jM/Screenshot-1.png',
    },

    {
      id: '6',
      titulo: 'HTML 5',
      lugar: 'Educación IT',
      tiempo: '',
      lugaresp: '',
      otros: 'Conocimientos principales:',
      detalle1: '•	Diferentes elementos HTML y sus respectivos atributos ',
      detalle2: '•	Uso de diferentes fuentes (google fonts)',
      detalle3: '	',
      detalle4: '	 ',
      logo: 'https://i.ibb.co/0qf83gV/images.jpg',
    },
    {
      id: '7',
      titulo: 'Mongo DB',
      lugar: 'Educación IT',
      tiempo: '',
      lugaresp: '',
      otros: 'Detalles:',
      detalle1: '• Creación de bases de datos con MongoDB y API RESTFul',
      detalle2: '• Diseño y desarrollo Web',
      detalle3: '• Uso de framework Express.Js y framework Handlebars',
      detalle4: '',
      logo: 'https://i.ibb.co/ncgMxFQ/5.png',
    },
    ]
