export const getMiCarreraDev = () => [
  {
    id: '1',
    titulo: 'ANGULAR',
    lugar: 'EDUCACIÓN IT',
    tiempo: '',
    lugaresp: '',
    otros: 'Materias Cursadas: Angular 8',
    detalle1: 'Conocimientos principales: ',
    detalle2: '•	Herramientas angular CLI - Arquitectura de una aplicación Angular ',
    detalle3: '•  Modelos de Formularios y sus validaciones',
    detalle4: '•  Inyección de Dependencias - crear servicios inyectables - Jerarquia de Servicios',
    detalle5: '•	Configuracion del cliente http - obtener datos de un JSON - ActivatedRoute - RouterModule  ',
    logo: 'https://i.ibb.co/x30Zm8p/aa.png',
  },
  {
    id: '2',
    titulo: 'REACT JS',
    lugar: 'EDUCACIÓN IT',
    tiempo: '',
    lugaresp: '',
    otros: 'Materias Cursadas: ReactJS - ReactJS Avanzado',
    detalle1: 'Conocimientos principales: ',
    detalle2: '•	Desarrollo con ReactJS ',
    detalle3: '•  Uso de: Componentes, Props y States ',
    detalle4: '•  Renderización desde el lado del cliente',
    detalle5: '•	Implementación de Redux y Routers ',
    logo: 'https://i.ibb.co/XtRZLVm/4.png',
  },
  {
    id: '3',
    titulo: 'JAVASCRIPT',
    lugar: 'EDUCACIÓN IT',
    tiempo: ' ',
    lugaresp: '',
    otros: 'Materias Cursadas: Javascript - Javascript Desarrollador Avanzado',
    detalle1: 'Conocimientos principales:',
    detalle2: '•	Eventos - Formularios y Validaciones con expresiones regulares',
    detalle3: '•	AJAX - Promesas - Fetch API - AsyncAwait',
    detalle4: '•	Prototipos - Programación orientada a objetos',
    detalle5: '•	Patrones de diseño',
    logo: 'https://i.ibb.co/GnJ4q7x/descarga.png',
  },
  {
    id: '4',
    titulo: 'JAVASCRIPT AWP',
    lugar: 'EDUCACIÓN IT',
    tiempo: '',
    lugaresp: '',
    otros: 'Materias Cursadas: JavaScript AWP',
    detalle1: 'Conocimientos principales',
    detalle2: '•	Desarrollo de aplicaciones con la posibilidad de trabajar sin conexión',
    detalle3: '•  Desarrollo de aplicaciones con apariencia de una app nativa instalada en el celular',
    logo: 'https://i.ibb.co/GCL82Z7/11png.png',
  },

    {
      id: '5',
      titulo: 'MAQUETADO WEB - HTML5 y CSS3',
      lugar: 'EDUCACIÓN IT',
      tiempo: '',
      lugaresp: '',
      otros: 'Materias Cursadas: Maquetacion Web - Maquetacion Web Avanzada',
      
      detalle1: 'Conocimientos Principales',
      detalle2: '• Diseños web responsivos',
      detalle3: '• Utilización de Bootstrap y Material',
      detalle4: '• APIs de dibujo (SVG, Canvas) - Diferente representación de colores y degradados',
      detalle5: '• Otros: Displays, Positions , Sprites, Animaciones, etc.',
      logo: 'https://i.ibb.co/0ZSF2jM/Screenshot-1.png',
    },

    {
      id: '6',
      titulo: 'HTML 5',
      lugar: 'EDUCACIÓN IT',
      tiempo: '',
      lugaresp: '',
      otros: 'Materias Cursadas: HTML5 Funcamentos Web',
      
      detalle1: 'Conocimientos Principales ',
      detalle2: '•	Diferentes elementos HTML y sus respectivos atributos ',
      detalle3: '•	Uso de diferentes fuentes (google fonts)',
      detalle4: '	',
      detalle5: '	 ',
      logo: 'https://i.ibb.co/0qf83gV/images.jpg',
    },
    {
      id: '7',
      titulo: 'MONGO DB',
      lugar: 'EDUCACIÓN IT',
      tiempo: '',
      lugaresp: '',
      otros: 'Materias Cursadas: Mongo DB Fundamentos',
      
      detalle1: 'Conocimientos Principales',
      detalle2: '• Creación de bases de datos con MongoDB y API RESTFul',
      detalle3: '• Diseño y desarrollo Web',
      detalle4: '• Uso de framework Express.Js y framework Handlebars',
      detalle5: '',
      logo: 'https://i.ibb.co/ncgMxFQ/5.png',
    },
    ]
