export const getMiCarrera = () => [
    {
      id: '1',
      titulo: 'CARACTERIZACIÓN SÍSMICA DE RESERVORIO',
      lugar: 'UNIVERSIDAD NACIONAL DE LA PLATA',
      tiempo: '   2019 ',
      lugaresp: 'Facultad de Ciencias Astronómicas y Geofísicas',
      otros: 'TESINA DE POSGRADO:',
      detalle1: '•	Carga de pozos y cubos sísmicos 3D',
      detalle2: '•	Puesta en profundidad de pozos',
      detalle3: '•	Inversión sísmica.',
      detalle4: '',
      logo: 'https://i.ibb.co/CJR5bMB/Screenshot-1.png',
    },
    {
      id: '2',
      titulo: 'ESPECIALIZACIÓN DE EXPLORACIÓN Y DESARROLLO DE HIDROCARBUROS',
      lugar: 'UNIVERSIDAD NACIONAL DE LA PLATA',
      tiempo: '   2017 - 2018',
      lugaresp: 'Facultad de Ciencias Naturales y Museo',
      otros: 'TESINA DE POSGRADO:',
      detalle1: '•	Carga y análisis de datos',
      detalle2: '•	Puesta en profundidad de pozos, interpretación de cubo sísmico 3D, generación de mapas estructurales e isopáquicos (software: Petrel).',
      detalle3: '•	Análisis petrofísicos y perfilajes de pozo.',
      detalle4: '•	Estimación probabilística de reservas de hidrocarburos y Análisis de Riesgo. ',
      logo: 'https://i.ibb.co/W5fkqhs/Screenshot-3.png',
    },
    {
      id: '3',
      titulo: 'LICENCIATURA EN GEOLOGÍA',
      lugar: 'UNIVERSIDAD NACIONAL DE LA PLATA',
      tiempo: '   2010 - 2016',
      lugaresp: 'Facultad de Ciencias Naturales y Museo',
      otros: '',
      detalle1: '',
      detalle2: '',
      detalle3: '',
      detalle4: '',
      logo: 'https://i.ibb.co/Bz1vhrb/Screenshot-4.png',
    },
    ]
