export const getMiCarrera = () => [
    {
      id: '1',
      titulo: 'CARACTERIZACION SISMICA DE RESERVORIO',
      lugar: 'UNIVERSIDAD NACIONAL DE LA PLATA',
      tiempo: '   2019 - 2020',
      lugaresp: 'Facultad de Ciencias Astronomicas y Geofisicas',
      otros: 'TESINA DE POSGRADO:',
      detalle1: '•	Carga de pozos y cubo sismicos 3D',
      detalle2: '•	Puesta en profundidad de pozos',
      detalle3: '•	Inversion sismica.',
      detalle4: '',
      logo: 'https://i.ibb.co/CJR5bMB/Screenshot-1.png',
    },
    {
      id: '2',
      titulo: 'ESPECIALIZACION DE EXPLORACION Y DESARROLLO DE HIDROCARBUROS',
      lugar: 'UNIVERSIDAD NACIONAL DE LA PLATA',
      tiempo: '   2019 - 2020',
      lugaresp: 'Facultad de Ciencias Naturales y Museo',
      otros: 'TESINA DE POSGRADO:',
      detalle1: '•	Carga y análisis de datos',
      detalle2: '•	Puesta en profundidad de pozos, interpretación del cubo sísmico 3D, generación de mapas estructurales e isopáquicos (software Petrel).',
      detalle3: '•	Análisis petrofísicos y perfilajes de pozo.',
      detalle4: '•	Estimación probabilística de reservas de hidrocarburos y Análisis de Riesgo. ',
      logo: 'https://i.ibb.co/W5fkqhs/Screenshot-3.png',
    },
    {
      id: '3',
      titulo: 'LICENCIATURA EN GEOLOGIA',
      lugar: 'UNIVERSIDAD NACIONAL DE LA PLATA',
      tiempo: '   2019 - 2020',
      lugaresp: 'Facultad de Ciencias Naturales y Museo',
      otros: '',
      detalle1: 'Todo muy lindo',
      detalle2: 'Catador de vinos de camajuana nivel 4',
      detalle3: '',
      detalle4: '',
      logo: 'https://i.ibb.co/Bz1vhrb/Screenshot-4.png',
    },
    ]
