export const getMisProyectos = () => [
  {
    id: '1',
    titulo: 'WEB PERSONAL',
    lugar: 'DESARROLLADA CON JAVASCRIPT',
    tiempo: ' ',
    lugaresp: '',
    otros: 'Secciones de la web:',
    detalle1: '•  Web tipo Single Page Aplication - Responsive ',
    detalle2: '•	Página principal: CV en inglés con información personal. Posee un diseño con un enfoque diferente al de esta App_CV ',
    detalle3: '•	Cada sección de la web está conformada por un Objeto (o varios) que se acoplan para generar la SPA',
    detalle4: '•	Posee : Formulario - Juego Snake - Web-Crítica ',
    detalle5: 'LINK: ',
    detalle6: 'https://leahrdt.github.io/',
    logo: 'https://i.ibb.co/p0hSMjL/Copia-de-FDK.png',
  },
  {
    id: '2',
    titulo: 'APP CLIMA',
    lugar: 'DESARROLLADA CON REAC.JS',
    tiempo: ' ',
    lugaresp: '',
    otros: 'Características:',
    detalle1: '•  Estado del clima, temperatura, nubosidad y presión de la ciudad que se seleccione',
    detalle2: '•	Pedidos asincrónicos a la API utilizando la librería axios',
    detalle3: '•	Wallpapers dinámicos dependiendo del estado del clima de la ciudad seleccionada',
    detalle4: '•	Responsive: maquetado con Bootstrap',
    detalle5: 'LINK: ',
    detalle6: 'https://leahrdt.github.io/AppClima/',
    logo: 'https://i.ibb.co/jvhnHnx/Copia-de-Copia-de-FDK.png',
  },
  {
    id: '3',
    titulo: 'JUEGO: Find The Key',
    lugar: 'DESARROLLADO CON JAVASCRIPT',
    tiempo: ' ',
    lugaresp: '',
    otros: 'Características:',
    detalle1: '•  Juego muy entretenido, en el cual debes encontrar una clave única de 4 dígitos',
    detalle2: '•	Responsive: maquetado con Bootstrap',
    detalle3: '•	Su código JS posee características como Programación Orientada a Objetos y Validaciones',
    detalle4: '•	Juego: ',
    detalle5: 'LINK: ',
    detalle6: 'https://leahrdt.github.io/gamejs/',
    logo: 'https://i.ibb.co/GxgV42B/Rident-Realtors.png',
  },
  {
    id: '4',
    titulo: 'ANGULAR 11 TEST',
    lugar: 'DESARROLLADA CON ANGULAR 11',
    tiempo: '',
    lugaresp: '',
    otros: 'Características:',
    detalle1: '•	Aplicación responsive - Diseñada con Bootstrap 5 - SPA',
    detalle2: '•  Carrete de fotos: posee llamados y edición a un API Rest a través de servicios inyectables',
    detalle3: '•  Formulario del tipo Reactive con Validaciones	',
    detalle3: '•  Utilización de Routes Module',
    detalle5: 'LINK:	',
    detalle6: 'https://leahrdt.github.io/Angular/',
    logo: 'https://i.ibb.co/tCBWM20/Copia-de-FDK-1.png',
  },
  {
    id: '5',
    titulo: 'APP CV DIGITAL',
    lugar: 'DESARROLLADA CON REACT JS',
    tiempo: '',
    lugaresp: '',
    otros: 'Características:',
    
    detalle1: '•	Esta Aplicacion',
    detalle2: '•	Función: aplicación web para presentar mis conocimientos y proyectos web',
    detalle3: '•  Diseño Responsive ',
    detalle4: '•  Framework de IU: Material-UI	',
    logo: 'https://i.ibb.co/51QgBdF/Copia-de-Copia-de-FDK-1.png',
  },


    ]
