export const getMisProyectos = () => [
  {
    id: '1',
    titulo: 'WEB PERSONAL',
    lugar: 'DESARROLLA CON JAVASCRIPT',
    tiempo: ' ',
    lugaresp: '',
    otros: 'Secciones de la web:',
    detalle1: '•  Web tipo Single Page Aplication - Responsive',
    detalle2: '•	Pagina principal: CV en ingles con información personal. Posee un diseño con un enfoque diferente al de esta App_CV ',
    detalle3: '•	Formulario validado a traves de Clases CSS y Exp-Regulares',
    detalle4: '•	Juego: Snake ',
    detalle5: 'Link: ',
    detalle6: 'https://leahrdt.github.io/',
    logo: 'https://i.ibb.co/JHrGZK1/Screenshot-5.png',
  },
  {
    id: '2',
    titulo: 'ANGULAR 11 TEST',
    lugar: 'DESARROLLADA CON ANGULAR 11',
    tiempo: '',
    lugaresp: '',
    otros: 'Características:',
    detalle1: '•	Aplicación responsive - Diseñada con Bootstrap 5 - SPA',
    detalle2: '•  Carrete de fotos: posee llamados y edición a un API Rest a través de servicios inyectables',
    detalle3: '•  Formulario del tipo Reactive con Validaciones	',
    detalle3: '•  Utilización de Routes Module',
    detalle5: 'Link:	',
    detalle6: 'https://leahrdt.github.io/Angular/',
    logo: 'https://i.ibb.co/HgZBCbN/descarga.png',
  },
  {
    id: '3',
    titulo: 'APP CV DIGITAL',
    lugar: 'DESARROLLADA CON REACT JS',
    tiempo: '',
    lugaresp: '',
    otros: 'Características:',
    
    detalle1: '•	Esta Aplicacion',
    detalle2: '•	Función: aplicación web para presentar mis conocimientos y proyectos web',
    detalle3: '•  Diseño Responsive ',
    detalle4: '•  Framework de IU: Material-UI	',
    logo: 'https://i.ibb.co/g7xWVd1/vector-cv-icon.jpg',
  },


    ]
